dependencies = []
description = "Dependency-Track is an intelligent Component Analysis platform that allows organizations to identify and reduce risk in the software supply chain."
destination_server = ["internal"]
flags = ["tools"]
languages = ["dockerfile", "shell"]
tier = 1
owner = "team-infosec@scalingo.com"
team = "Infosec"
version = "1.0.0"
