# Scalingo-specific workflow. Not part of upstream, kept separate to avoid rebase conflicts.
name: Mirror Container Image (Scalingo)

on:
  registry_package:
    types:
    - published

permissions: { }

jobs:
  mirror-to-dockerhub:
    name: Mirror to Docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # * Only mirror images for the Scalingo fork.
    # * Only mirror the apiserver image, published as scalingo/dependency-track.
    # * Deal with multiplatform images where only the final manifest has a tag name.
    #   amd64 and arm64 image variants are published without tag name.
    if: |
      github.repository_owner == 'Scalingo'
        && github.event.registry_package.package_type == 'CONTAINER'
        && github.event.registry_package.name == 'apiserver'
        && github.event.registry_package.package_version.container_metadata.tag.name != ''
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # tag=v4.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Setup Crane
      uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # tag=v0.5
    - name: Mirror image to Docker Hub
      env:
        PACKAGE_NAMESPACE: ${{ github.event.registry_package.namespace }}
        PACKAGE_TAG: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}
      run: |
        SRC_IMAGE="ghcr.io/${PACKAGE_NAMESPACE}/apiserver:${PACKAGE_TAG}"
        DST_IMAGE="docker.io/scalingo/dependency-track:${PACKAGE_TAG}"
        DST_LATEST="docker.io/scalingo/dependency-track:latest"

        crane copy "${SRC_IMAGE}" "${DST_IMAGE}"
        crane copy "${SRC_IMAGE}" "${DST_LATEST}"
